<?php
/**
 * Composes and parses Spart webhook session IDs.
 *
 * @package Spart\WooCommerce\Checkout
 */

declare(strict_types=1);

namespace Spart\WooCommerce\Checkout;

/**
 * Value object that composes and parses a Spart webhook session ID.
 *
 * Format: spart-wc-<8-hex>-<order_id>
 * Maximum length: 64 characters.
 */
final class SessionIdComposer {

	/**
	 * Common prefix for all session IDs generated by this plugin.
	 */
	public const PREFIX = 'spart-wc';

	/**
	 * Maximum allowed length for a composed session ID.
	 */
	private const MAX_LENGTH = 64;

	/**
	 * 8-character lowercase hex site token.
	 *
	 * @var string
	 */
	private string $site_token;

	/**
	 * Constructor.
	 *
	 * @param string $site_token 8-character lowercase hex string.
	 * @throws \InvalidArgumentException When the token is not exactly 8 hex chars.
	 */
	public function __construct( string $site_token ) {
		if ( 8 !== strlen( $site_token ) || ! ctype_xdigit( $site_token ) ) {
			throw new \InvalidArgumentException(
				'site_token must be exactly 8 lowercase hex characters.'
			);
		}
		$this->site_token = strtolower( $site_token );
	}

	/**
	 * Compose a session ID for the given order.
	 *
	 * @param int|string $order_id WooCommerce order ID (int or numeric string).
	 * @return string Session ID string.
	 * @throws \OverflowException When the composed ID would exceed MAX_LENGTH.
	 */
	public function compose( int|string $order_id ): string {
		$id = self::PREFIX . '-' . $this->site_token . '-' . $order_id;

		if ( strlen( $id ) > self::MAX_LENGTH ) {
			throw new \OverflowException(
				'Session ID exceeds the maximum allowed length.'
			);
		}

		return $id;
	}

	/**
	 * Derive the 8-hex site token from the site's home URL.
	 *
	 * This is the canonical source-of-truth used at plugin activation.
	 *
	 * @param string $home_url The site's home URL (typically from home_url()).
	 * @return string 8-character lowercase hex string.
	 */
	public static function derive_site_token( string $home_url ): string {
		return substr( hash( 'sha256', $home_url ), 0, 8 );
	}

	/**
	 * Extract the WooCommerce order ID embedded in a session ID.
	 *
	 * @param string $session_id A session ID previously created by compose().
	 * @return int|null Order ID, or null when the string is not a valid session ID.
	 */
	public static function extract_order_id( string $session_id ): ?int {
		// Format: spart-wc-<8hex>-<digits>.
		if ( ! preg_match( '/^spart-wc-[0-9a-f]{8}-(\d+)$/', $session_id, $m ) ) {
			return null;
		}
		return (int) $m[1];
	}

	/**
	 * Check whether a session ID belongs to the given site token.
	 *
	 * @param string $session_id  The session ID to inspect.
	 * @param string $site_token  8-character lowercase hex token.
	 * @return bool True when the embedded token matches.
	 */
	public static function belongs_to_site_token( string $session_id, string $site_token ): bool {
		$prefix = self::PREFIX . '-' . strtolower( $site_token ) . '-';
		return str_starts_with( $session_id, $prefix );
	}
}
